-- Lute and Lune mapping based on module output (Not fully tested)
--[[
File system
require("@lune/fs")
require("@lute/fs"
require("@lute/io") - C++?

-- Luau
require("@lute/luau")
require("@lune/luau")

-- Networking
require("@lute/net")
require("@lune/net")

-- Process
require("@lute/process")
require("@lune/process") / require("@lute/system") extra details??

-- Task
require("@lute/task")
require("@lune/task")

-- Time
require("@lute/time")
require("@lune/datetime")

-- Json / whatever I forgor word
require("@lune/serde")

-- Roblox
require("@lune/roblox")

-- prompts
require("@lune/stdio")

-- Uncategorized

require("@lune/regex")
require("@lute/crypto")
require("@lute/debugger")
require("@lute/vm")
require("@lute/crypto")
require("@lute/crypto")
require("@lute/crypto")
]]

--[[

PS C:\Users\Bluee\OneDrive\Desktop\Develop\Roblox\ProtonLuau> lune run main.luau
removeDir <function>
move <function>
writeDir <function>
isFile <function>
metadata <function>
copy <function>
writeFile <function>
isDir <function>
removeFile <function>
readDir <function>
readFile <function>
PS C:\Users\Bluee\OneDrive\Desktop\Develop\Roblox\ProtonLuau> lute run main.luau
close	function: 0x0000020169bb6ff8
readIntoBuffer	function: 0x0000020169bb6fc0
listdir	function: 0x0000020169bb6d58
remove	function: 0x0000020169bb6f88
mkdir	function: 0x0000020169bb6d90
watch	function: 0x0000020169bb6ea8
stat	function: 0x0000020169bb6f50
rmdir	function: 0x0000020169bb6d20
type	function: 0x0000020169bb6ee0
write	function: 0x0000020169bb7030
link	function: 0x0000020169bb6e70
open	function: 0x0000020169bb70a0
read	function: 0x0000020169bb7068
exists	function: 0x0000020169bb6f18
symlink	function: 0x0000020169bb6e38
move	function: 0x0000020169bb6dc8
copy	function: 0x0000020169bb6e00
PS C:\Users\Bluee\OneDrive\Desktop\Develop\Roblox\ProtonLuau>

]]

require("@lune/serde")
require("@lute/fs")
